### ISSUE TITLE
Pandas support for Delta Lake

### ISSUE THREAD

**Issue by jackwellsxyz** [delta-io/delta#467] opened 2020-06-29 02:44 UTC
Hi Delta Lake community, I had asked the Pandas team to investigate adding Delta Lake support since I bounce between Pandas and Spark, and they said they wouldn't support it since it looks like Delta Lake seems tied to Spark for its APIs (see [pandas issue 35017](https://github.com/pandas-dev/pandas/issues/35017)). Is this true?

> The only stable public APIs, currently provided by Delta Lake, are through the DataFrameReader/Writer (i.e. spark.read, df.write, spark.readStream and df.writeStream). Options to these APIs will remain stable within a major release of Delta Lake (e.g., 1.x.x).
> 
> All other interfaces in this library are considered internal, and they are subject to change across minor/patch releases.

I personally would love to start using Delta Lake more extensively in my machine learning projects, but I'd be nervous if I had to give up on being able to read it in to my laptop for exploratory data analysis. Thanks for considering!

**Comment by brkyvz** [comment] 2020-06-29 18:47
@jackwellsxyz Can you use koalas? https://koalas.readthedocs.io/en/latest/reference/api/databricks.koalas.read_delta.html

**Comment by jackwellsxyz** [comment] 2020-07-03 03:58
Thanks @brkyvz for the feedback! Ultimately, I'm afraid that if I store data in Delta Lake format, then I tie myself to only analyzing it using Spark, as koalas only runs on Spark if I'm not mistaken. It would be nice to be able to open the data in pandas in a Jupyter notebook on my local laptop as well. Are there any architectural limitations of the Delta Lake file format that would prevent it from being opened on a local machine with pandas? For example, parquet and json formats are both well supported in pandas via the Apache Arrow and fastparquet libraries.

**Comment by manucohenyashar** [comment] 2020-09-22 13:06
I agree. It makes no sense to bind Delta to Spark. Delta is a storage format while Spark is an execution engine. Modern data management tend to separate storage from compute (unlike to old days of Hadoop). Exposing Delta to Pandas will open the doors to countless use cases.

**Comment by vmesel** [comment] 2020-09-28 11:23
I agree with @manucohenyashar! In the company I work for, we need to use the delta formats on the gold data layer to enable us keep versioning and continue improving our pipeline.

**Comment by philMarius** [comment] 2020-12-17 10:31
Is there an update on this?

**Comment by houqp** [comment] 2021-03-22 18:37
For those who need access to delta lake natively outside of JVM, i recommend giving https://github.com/delta-io/delta-rs a try. Its python binding already supports reading delta tables using pandas, see examples at https://github.com/delta-io/delta-rs/tree/main/python#usage.

I think it's best to leave the official reference implementation depend on spark because that's the only way to process large scale delta tables.

**Comment by Sutyke** [comment] 2021-03-25 06:04
Pandas support already parquet. Pandas contributors would implement delta lake if databricks creates the same pyarrow connector as for parquet. Can databricks help? 

Below is pandas contributor reply:
https://github.com/pandas-dev/pandas/issues/40573

**Comment by houqp** [comment] 2021-03-25 06:34
@Sutyke see https://github.com/delta-io/delta-rs/tree/main/python#usage, we already support processing delta tables with native pandas.

**Comment by manucohenyashar** [comment] 2021-03-26 19:55
The idea is not only to read delta tables to a data frame but also to
persist a data frame to a delta table.
I don't see that supported today.
In short, it should be possible to work with delta tables without using
Spark anywhere in the pipeline.

**Comment by houqp** [comment] 2021-03-27 00:41
@manucohenyashar that's our medium term goal, we are will be using delta-rs in https://github.com/delta-io/kafka-delta-ingest to perform delta table write for streaming input, then process them in spark downstream. Delta-rs currently already have append delta table write working in a PoC, we are working on making it production ready.

**Comment by djouallah** [comment] 2021-05-27 23:49
any update on this,  is python now able to create Delta table without spark ?

**Comment by houqp** [comment] 2021-05-28 03:35
@djouallah yes, see https://delta-io.github.io/delta-rs/python/

**Comment by manucohenyashar** [comment] 2021-05-28 12:44
The question is if it is possible to *CREATE *a new delta table *without *using
spark in python?

Manu

**Comment by djouallah** [comment] 2021-10-11 21:13
@MrPowers thanks, I think the issue is obviously still not addressed, need to write delta without spark using only python.

**Comment by GraemeCliffe-inspirato** [comment] 2022-02-22 14:23
@houqp is this the file you envision the API exposure being handled in? Or should a new file be created for this purpose? https://github.com/delta-io/delta/blob/master/python/delta/tables.py

**Comment by zsxwing** [comment] 2022-02-23 04:26
Closing this. https://github.com/delta-io/delta-rs/pull/294 has added an API to load a Delta table as a pandas dataframe.

**Closed by zsxwing** 2022-02-23 04:26 UTC

**Comment by djouallah** [comment] 2022-02-23 05:21
@zsxwing  sorry the feature request is how to *write* a delta table from Python  without Spark? is this supported

**Comment by houqp** [comment] 2022-02-23 05:35
@djouallah this is being tracked in https://github.com/delta-io/delta-rs/issues/542 and @wjones127 is driving it.
