### ISSUE TITLE
maxBytesPerTrigger  setting not working as expected while streaming from Delta lake table

### ISSUE THREAD

**Issue by mahanoor786** [delta-io/delta#843] opened 2021-11-24 13:13 UTC
According to [public documentation](https://docs.databricks.com/delta/delta-streaming.html#id4), it states that when we specify maxBytesPerTrigger, it will try to fetch apprx that size of data.

**Scenario:** 
I have delta commits coming in of size ~10MB. Though I specify 65536/65536b, it is always fetching the whole version df in a micro batch instead of 64KB worth of data. 

Can u pls let me know if I am missing something. And also, please update documentation with some example for this use case. 

`    df = ( 
SPARK.readStream.format("delta") 
        .option("ignoreChanges", "true") 
        .option("maxBytesPerTrigger", "65536b") 
        .load(path)
    )`

NOTE: My delta lake table consists of data in parquet format

**Comment by mahanoor786** [comment] 2021-11-24 13:41
@zsxwing , @brkyvz Can u pls take a look

**Comment by nigelmeakins** [comment] 2022-03-04 20:11
Having searched the source code I'm not able to see where this is being implemented. Looking at the DeltaOptions class, line 192,
core/src/main/scala/org/apache/spark/sql/delta/DeltaOptions.scala

 the MAX_BYTES_PER_TRIGGER_OPTION entry is missing from the Set validOptionKeys. Does this mean it is still awaiting implementation? I too am not seeing the expected behaviour for this option setting.

**Comment by vkorukanti** [comment] 2022-03-04 20:29
@nigelmeakins I see this option is being used in `[DeltaSource](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/sources/DeltaSource.scala#L525)`. From the description it looks like a best effort option. If the files are much larger than the set limit, it is not going to respect the limit set.

**Comment by nigelmeakins** [comment] 2022-03-04 22:46
Okay, thanks for your prompt reply. Would it be possible to have the documentation expanded to this effect? At present it is not completely transparent how this affects streaming input rate.

**Comment by zsxwing** [comment] 2022-04-15 16:33
@nigelmeakins we have updated our doc with the following content ( https://docs.delta.io/latest/delta-streaming.html#limit-input-rate ):

> maxBytesPerTrigger: How much data gets processed in each micro-batch. This option sets a “soft max”, meaning that a batch processes approximately this amount of data and may process more than the limit in order to make the streaming query move forward in cases when the smallest input unit is larger than this limit. If you use Trigger.Once for your streaming, this option is ignored. This is not set by default.

I'm going to close this. Feel free to re-open this issue if you have any more suggestions to the documentation.

**Closed by zsxwing** 2022-04-15 16:33 UTC
Labels: bug, acknowledged

**Comment by justinTM** [comment] 2022-11-09 09:46
i'm pretty sure i'm having this issue. with ~1mil rows, and `maxBytesPerTrigger` set to even `1K`, i am still getting all 1 mil rows in my batch function:

```python
def batch_function(cdf_df: DataFrame, batch_id, job: RevenueDataCuration):
    _print(cdf_df.count())

(
    spark.readStream
    .table("_temp_max_bytes_calc")
    .select("id", "year", "month")
    .drop_duplicates()
    .writeStream
    .foreachBatch(batch_func)
    .trigger(processingTime="5 seconds")
    .queryName("my query")
    .start()
)
```
```console
[2022-11-09T09:30:13.113617] 1215090
[2022-11-09T09:30:54.019307] Stopping query...
[2022-11-09T09:30:56.236951] Awaiting termination...
Out[13]: <pyspark.sql.streaming.query.StreamingQuery at 0x7fc4ec225cd0>
```
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/9123665/200795877-3e08f267-2f18-4e62-af89-b63476209e1b.png">
