### ISSUE TITLE
AnalysisException: Attribute name contains invalid character(s) issue

### ISSUE THREAD

**Issue by rambabu-posa** [delta-io/delta#462] opened 2020-06-22 13:30 UTC
Exception in thread "main" org.apache.spark.sql.AnalysisException: Attribute name "Code région" contains invalid character(s) among " ,;{}()\n\t=". Please use alias to rename it.;

**Comment by rambabu-posa** [comment] 2020-06-22 13:39
Not only this column name (with special characters), normal column like "Transacation description" is also failing with same error.

That means if a Spark DataFrame reads a CSV file with column names( having spaces), its throwing same AnalysisException exception.

Is there any way to fix this issue with default character adding to that space like
"Transacation description"
to
"Transacation_description"

Or any other solution to solve this scenario please?

**Comment by brkyvz** [comment] 2020-06-22 15:49
You can use the `withColumnRenamed` function of DataFrames to rename your columns, or you can alias columns in your select statement with `alias`, e.g.
```scala
select(col("Transacation description").alias("Transacation_description"))
```

**Comment by rambabu-posa** [comment] 2020-06-22 16:01
Yes we can do it programatically. Do we have any option to fix it without doing so?
I think, we don't need to rename column names in Spark, it works very well without doing so.

**Comment by brkyvz** [comment] 2020-06-22 16:05
Parquet doesn't allow storing such column names. I'd say it's better engineering practice for you to follow some convention yourself and fix the names rather than having some system arbitrarily fix it for you.

**Comment by rambabu-posa** [comment] 2020-06-23 11:00
Im able to do the same operation using DataFrame API like
    df.write.format("parquet").save("data/par_data")

I would say its feature "Delta Lake" that it is enforcing to follow that good practice.

**Comment by tdas** [comment] 2020-06-23 20:02
That has indeed been one of our core design principle - an opinionated view of how to manage data without shooting yourself in the foot.

**Comment by zsxwing** [comment] 2021-04-07 03:46
Closing this. Invalid characters are disallowed by design.

**Closed by zsxwing** 2021-04-07 03:46 UTC

**Comment by surya1527** [comment] 2022-02-22 07:44
> Parquet doesn't allow storing such column names. I'd say it's better engineering practice for you to follow some convention yourself and fix the names rather than having some system arbitrarily fix it for you.


for c in df.columns:
    df = df.withColumnRenamed(c, c.replace( ";" , ""))


That worked fine in case
