### ISSUE TITLE
Vacuum failed on file deletion, but SparkJob success

### ISSUE THREAD

**Issue by yogyang** [delta-io/delta#431] opened 2020-05-19 03:40 UTC
when executing the Vaccum, the deletion of S3 files failed on some permission errors, but from the frontend, the Spark UI / notebook didn't give me any indicates of the failure, I wouldn't even know my Vacuum failed unless I check the log.

saw the codes here 
https://github.com/delta-io/delta/blob/1e01dbbc82d2ea897aa204fcf4d39b4109bbbd7d/src/main/scala/org/apache/spark/sql/delta/util/DeltaFileOperations.scala#L219
,it seems to cover up the failure on purpose 
So, any plan to make the failure exposed to the user?

**Comment by liwensun** [comment] 2020-05-19 23:31
Hi @yogyang Thanks for reporting. I agree that we should fail in permission errors and the exception we catch there is too broad. 

Labeled in this as a bug and we will fix it.

**Comment by zsxwing** [comment] 2021-04-07 03:52
Duplicate of #464

**Closed by zsxwing** 2021-04-07 03:52 UTC
Labels: bug
