### ISSUE TITLE
Error while adding partition to existing delta table

### ISSUE THREAD

**Issue by shahsunil** [delta-io/delta#1502] opened 2022-11-28 20:51 UTC
I have one delta table created as

CREATE TABLE IF NOT EXISTS global.T_RUN_DATA
(
	ID INT NOT NULL,
	RUN_TIME STRING NOT NULL,
	NAME STRING NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	CREATE_BY STRING NOT NULL,
	UPDATE_DATE TIMESTAMP,
	UPDATE_BY STRING
)
USING delta
location 's3://dummy_bucket/global/run_data';

Two rows inserted.

INSERT INTO  global.T_CREDIT_MODEL_RUN_DATA (ID , RUN_TIME, NAME ,CREATE_DATE ,CREATE_BY ,UPDATE_DATE, UPDATE_BY) values (1, '11282022034900', 'Name1', now(), 'user1', null, null)

INSERT INTO  global.T_CREDIT_MODEL_RUN_DATA (ID , RUN_TIME, NAME ,CREATE_DATE ,CREATE_BY ,UPDATE_DATE, UPDATE_BY) values (2, '11282022034901', 'Name2', now(), 'user1', null, null)

Now, if I try to add partition on this table with
ALTER TABLE global.T_RUN_DATA ADD PARTITION (ID= 1);

I am getting below error.

Error in SQL statement: AnalysisException: Operation not allowed: `ALTER TABLE ADD PARTITION` is not supported for Delta tables: `global`.`t_run_data`;
AlterTableAddPartitionCommand `global`.`t_run_data`, [(Map(ID -> 1),None)], false

**Comment by zsxwing** [comment] 2022-11-28 21:34
Delta doesn't support the legacy partition commands, such as ADD PARTITION or [DROP PARTITION](https://github.com/delta-io/delta/issues/1461). Delta manages all of file paths in its metadata.

For your example, you can just run the following commands without `ALTER TABLE ADD PARTITION`
```
CREATE TABLE IF NOT EXISTS global.T_RUN_DATA
(
ID INT NOT NULL,
RUN_TIME STRING NOT NULL,
NAME STRING NOT NULL,
CREATE_DATE TIMESTAMP NOT NULL,
CREATE_BY STRING NOT NULL,
UPDATE_DATE TIMESTAMP,
UPDATE_BY STRING
)
USING delta
PARTITIONED BY (ID) ---  <--  this is the diff
location 's3://dummy_bucket/global/run_data';

INSERT INTO global.T_CREDIT_MODEL_RUN_DATA (ID , RUN_TIME, NAME ,CREATE_DATE ,CREATE_BY ,UPDATE_DATE, UPDATE_BY) values (1, '11282022034900', 'Name1', now(), 'user1', null, null)

INSERT INTO global.T_CREDIT_MODEL_RUN_DATA (ID , RUN_TIME, NAME ,CREATE_DATE ,CREATE_BY ,UPDATE_DATE, UPDATE_BY) values (2, '11282022034901', 'Name2', now(), 'user1', null, null)
```

**Comment by shahsunil** [comment] 2022-11-28 21:55
@zsxwing  Thanks for quick reply.

We can add partition during table creation itself. But to add the partition for existing table, we need to recreate the table by providing partition details. Is this correct understanding?

**Comment by zsxwing** [comment] 2022-11-28 22:11
Do you mean you want to change a NEW partition column to an existing table? This is not what `ALTER TABLE ADD PARTITION` does even for Hive either. For example, `ALTER TABLE global.T_RUN_DATA ADD PARTITION (ID= 1);` will add a directory for the partition `ID = 1` but your table needs to be created using partitioned by `PARTITIONED BY (ID)` as well. If you want to change the partition columns in an existing table, you can use REPLACE to rewrite the table like this

```
REPLACE TABLE global.T_RUN_DATA
USING delta
PARTITIONED BY (ID)
SELECT * FROM global.T_RUN_DATA
```

**Comment by shahsunil** [comment] 2022-11-28 22:18
yes, I want to add new partition column to an existing table. I got it now that we can do it by REPLACE to rewrite table. Thanks.

**Comment by zsxwing** [comment] 2022-11-28 22:24
Cool. Closing this issue as this is not a bug.

**Closed by zsxwing** 2022-11-28 22:24 UTC
Labels: question
