### ISSUE TITLE
Delta readStream.table fails with "Delta does not support specifying the schema at read time." even when schema is not specified.

### ISSUE THREAD

**Issue by shivampanicker16** [delta-io/delta#783] opened 2021-09-21 00:41 UTC
Sample code
```scala
import org.apache.spark.sql.SparkSession

val    spark = SparkSession
  .builder()
  .appName("Save parsed Data to s3 Test")
  .master("local[*]")
  .config("spark.driver.bindAddress", "127.0.0.1")
  .getOrCreate()

spark.sql("CREATE DATABASE helios LOCATION '/tmp/delta'")
spark.sql("""CREATE TABLE IF NOT EXISTS  helios.bronze (
            | _datatypeId STRING,
            |_guid STRING,
            |_tenantId STRING,
            |_ingestTime STRING,
            |data STRING
            |)
            |USING DELTA
            |""".stripMargin)

val columns = Seq(
  "_datatypeId",
  "_guid",
  "_tenantId",
  "_ingestTime",
  "data"
)
val data = Seq(
  (
    "datatype1",
    "_guid1",
    "_tenantId1",
    "_ingestTime1",
    "{\"data1\": \"data1\"}"
  ),
  (
    "datatype2",
    "_guid2",
    "_tenantId2",
    "_ingestTime2",
    "{\"data2\": \"data2\"}"
  ),
  (
    "datatype3",
    "_guid3",
    "_tenantId3",
    "_ingestTime3",
    "{\"data3\": \"data3\"}"
  )
)


spark.sql("""CREATE TABLE IF NOT EXISTS  helios.silver (
            | _datatypeId STRING
            |)
            |USING delta
            |""".stripMargin)


val dataFrame = spark.createDataFrame(data).toDF(columns: _*)

dataFrame.write.format("delta").mode("append").saveAsTable("helios.bronze")

val df = spark.readStream.format("delta").table("helios.bronze")

df.select("_datatypeId").writeStream.format("delta").toTable("helios.silver").processAllAvailable()
```

The above code fails with "_org.apache.spark.sql.AnalysisException: Delta does not support specifying the schema at read time._" There is no schema specified. Detailed error log attached.

[delta-exception.txt](https://github.com/delta-io/delta/files/7199366/delta-exception.txt)

**Comment by shivampanicker16** [comment] 2021-09-21 00:46
Delta lib used--    
        <dependency>
            <groupId>io.delta</groupId>
            <artifactId>delta-core_2.12</artifactId>
            <version>1.0.0</version>
        </dependency>

**Comment by zsxwing** [comment] 2021-09-30 06:19
@shivampanicker16 Looks like it's because you are missing the following required configs:

> --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"

They are required for any table APIs.

I cannot reproduce the error after setting the above configs.

**Comment by zsxwing** [comment] 2021-10-04 16:40
Closing this as this looks like a user error.

**Closed by zsxwing** 2021-10-04 16:40 UTC
