### ISSUE TITLE
Race when saving .checkpoint.parquet sometimes saves file with the wrong S3 permissions when assuming role.

### ISSUE THREAD

**Issue by trega3** [delta-io/delta#231] opened 2019-10-30 20:59 UTC
Hello,

My organization runs an EMR cluster in one Amazon account, but we save data to an S3 bucket (through EMRFS) in another account. In order to accomplish this, we configure the SparkSession as such...

```
val FS_S3A_ACCESS_KEY = "spark.hadoop.fs.s3a.access.key"
val FS_S3A_SECRET_KEY = "spark.hadoop.fs.s3a.secret.key"
val FS_S3A_SESSION_TOKEN = "spark.hadoop.fs.s3a.session.token"
 
builder.config(FS_S3A_ACCESS_KEY, s3Credentials.getAccessKeyId)
.config(FS_S3A_SECRET_KEY, s3Credentials.getSecretAccessKey)
.config(FS_S3A_SESSION_TOKEN, s3Credentials.getSessionToken)
```

This configuration works fine; however, very occasionally a race occurs when saving the .checkpoint.parquet file in which the file is written with the EMR account's privileges instead of the role-assumed privileges indicated above. I should note that the AWS environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, etc.) ARE set for the EMR account's privileges-- this is why we override the s3 keys at runtime, as [by default spark will retrieve s3 keys from the environment](https://github.com/apache/spark/blob/e1ea806b3075d279b5f08a29fe4c1ad6d3c4191a/core/src/main/scala/org/apache/spark/deploy/SparkHadoopUtil.scala#L438).

After investigating the checkpoint logic, I found this parquet file is not written out using the spark configuration. Instead, the [Checkpoints class calls Job.getInstance(), and retrieves a configuration from that](https://github.com/delta-io/delta/blob/adaee91212233ae5391b9bf4e069e680d1fae4da/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala#L221). This [will be a new configuration](https://github.com/apache/hadoop-mapreduce/blob/trunk/src/java/org/apache/hadoop/mapreduce/Job.java#L169) which does not contain any of the configurations defined in the SparkSession. In the logs, we can see odd things happening, such as the ParquetOutputCommitter being used for writing the .checkpoint.parquet file instead of the EmrOptimizedSparkSqlParquetOutputCommitter as is defined in our configuration.

What I cannot explain is why this error is only occasionally happening. Most of the time the .checkpoint.parquet file is written with the permissions as configured.

I hope this helps.

Thanks

**Comment by tdas** [comment] 2019-10-31 02:50
This is interesting. Not using the SparkSession configuration probably is a bug that should be fixed. But I dont know why it fails only intermittently. There may be funny race conditions going on during the creation of the new configuration object, it randomly may or may not pick up the correct credential stuff from somewhere.... hadoop confs are always a mystery to debug. 

The fix should be easy. Instead of using the new job's configuration, you can create the conf object using `spark.sessionState.newHadoopConf` (see other places where this is used. It would be awesome if you can actually try out this idea on your setup since we know that it reproduces the issue reliably.

**Comment by trega123** [comment] 2019-10-31 14:16
Thank you for the quick response. I will try and get time approved for next sprint for me to fork delta lake with your suggested change and report back.

**Comment by pranavanand** [comment] 2020-03-26 21:42
Hi @trega123 , Were you able to find time to make the suggested change?

**Comment by steveloughran** [comment] 2020-09-21 13:15
You could always change the fs.s3a.credential.provider list to remove the one which picks up the IAM session credential from the EC2 per-VM http server.

**Comment by travis-c-lagrone** [comment] 2020-11-20 13:37
This issue manifests in Delta Lake for Azure Data Lake Storage as well.

**Closed** 2021-10-08 19:11 UTC
Labels: bug
