### ISSUE TITLE
Vacuum fails with Delta version 1.0.0 on AWS Glue 3.0 (Spark 3.1.1)

### ISSUE THREAD

**Issue by julianste** [delta-io/delta#841] opened 2021-11-22 16:25 UTC
## Steps to reproduce
Setup AWS Glue 3.0 job (which is Spark 3.1.1) and configure following jars / python libs:
    - delta-core_2.12-1.0.0.jar ([should be compatible with Spark 3.1.x](https://docs.delta.io/latest/releases.html))
    - delta-spark = "==1.0.0"
    - pyspark = "==3.1.1"

The following lines lead to an error (**Stream is corrupted**) when executed with AWS Glue 3.0 environment
```
delta_table = DeltaTable.forPath(spark_session, data_path)
delta_table.vacuum(0)
```

We also tried different retention periods with same results.

Everything works fine with Glue 2.0 (Spark 2.4.3) and delta-core_2.11-0.6.1.jar, so our setup should be good.
Is Glue 3.0 compatible with Delta 1.0.0?

## Stack Trace:

2021-11-22 15:42:53,873 ERROR [main] glue.ProcessLauncher (Logging.scala:logError(73)): Error from Python:Traceback (most recent call last):
  File "/tmp/vacuum.py", line 23, in <module>
    main()
  File "/tmp/vacuum.py", line 19, in main
    delta_table.vacuum(0)
  File "/tmp/delta_spark-1.0.0-py3-none-any.whl/delta/tables.py", line 211, in vacuum
    return DataFrame(jdt.vacuum(float(retentionHours)), self._spark._wrapped)
  File "/tmp/py4j-0.10.9-py2.py3-none-any.whl/py4j/java_gateway.py", line 1305, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/opt/amazon/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/tmp/py4j-0.10.9-py2.py3-none-any.whl/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o403.vacuum.
: org.apache.spark.SparkException: Job aborted due to stage failure: ResultStage 17 ($anonfun$withThreadLocalCaptured$1 at FutureTask.java:266) has failed the maximum allowable number of times: 4. Most recent failure reason: org.apache.spark.shuffle.FetchFailedException: Stream is corrupted 	at org.apache.spark.storage.ShuffleBlockFetcherIterator.throwFetchFailedException(ShuffleBlockFetcherIterator.scala:772) 	at org.apache.spark.storage.BufferReleasingInputStream.read(ShuffleBlockFetcherIterator.scala:845) 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) 	at java.io.DataInputStream.readInt(DataInputStream.java:387) 	at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$2$$anon$3.readSize(UnsafeRowSerializer.scala:113) 	at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$2$$anon$3.next(UnsafeRowSerializer.scala:129) 	at org.apache.spark.sql.execution.UnsafeRowSerializerInstance$$anon$2$$anon$3.next(UnsafeRowSerializer.scala:110) 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:494) 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459) 	at org.apache.spark.util.CompletionIterator.next(CompletionIterator.scala:29) 	at org.apache.spark.InterruptibleIterator.next(InterruptibleIterator.scala:40) 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459) 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:351) 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898) 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337) 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) 	at org.apache.spark.scheduler.Task.run(Task.scala:131) 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497) 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439) 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748) Caused by: java.io.IOException: Stream is corrupted 	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:200) 	at net.jpountz.lz4.LZ4BlockInputStream.refill(LZ4BlockInputStream.java:226) 	at net.jpountz.lz4.LZ4BlockInputStream.read(LZ4BlockInputStream.java:157) 	at org.apache.spark.storage.BufferReleasingInputStream.read(ShuffleBlockFetcherIterator.scala:841) 	... 25 more 
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2465)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2414)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2413)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2413)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskCompletion(DAGScheduler.scala:1871)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2676)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2621)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2610)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:914)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2238)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2259)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2278)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2303)
	at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1030)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:1029)
	at org.apache.spark.sql.execution.SparkPlan.executeCollectIterator(SparkPlan.scala:402)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec.org$apache$spark$sql$execution$exchange$BroadcastExchangeExec$$doComputeRelation(BroadcastExchangeExec.scala:178)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec$$anon$1.doCompute(BroadcastExchangeExec.scala:171)
	at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec$$anon$1.doCompute(BroadcastExchangeExec.scala:167)
	at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$compute$1(AsyncDriverOperation.scala:73)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:224)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionId$1(SQLExecution.scala:207)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:253)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:204)
	at org.apache.spark.sql.execution.AsyncDriverOperation.compute(AsyncDriverOperation.scala:67)
	at org.apache.spark.sql.execution.AsyncDriverOperation.$anonfun$computeFuture$1(AsyncDriverOperation.scala:53)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withThreadLocalCaptured$1(SQLExecution.scala:275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.checkNoFailures(AdaptiveExecutor.scala:147)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.doRun(AdaptiveExecutor.scala:88)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.tryRunningAndGetFuture(AdaptiveExecutor.scala:66)
	at org.apache.spark.sql.execution.adaptive.AdaptiveExecutor.execute(AdaptiveExecutor.scala:57)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.$anonfun$getFinalPhysicalPlan$1(AdaptiveSparkPlanExec.scala:184)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.getFinalPhysicalPlan(AdaptiveSparkPlanExec.scala:183)
	at org.apache.spark.sql.execution.adaptive.AdaptiveSparkPlanExec.executeToIterator(AdaptiveSparkPlanExec.scala:416)
	at org.apache.spark.sql.Dataset.$anonfun$toLocalIterator$1(Dataset.scala:3036)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3724)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
	at org.apache.spark.sql.execution.SQLExecution$.executeQuery$1(SQLExecution.scala:110)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:135)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withTracker(SQLExecution.scala:232)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:135)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:253)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:134)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:772)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3722)
	at org.apache.spark.sql.Dataset.toLocalIterator(Dataset.scala:3034)
	at org.apache.spark.sql.delta.commands.VacuumCommandImpl.delete(VacuumCommand.scala:325)
	at org.apache.spark.sql.delta.commands.VacuumCommandImpl.delete$(VacuumCommand.scala:309)
	at org.apache.spark.sql.delta.commands.VacuumCommand$.delete(VacuumCommand.scala:49)
	at org.apache.spark.sql.delta.commands.VacuumCommand$.$anonfun$gc$1(VacuumCommand.scala:239)
	at com.databricks.spark.util.DatabricksLogging.recordOperation(DatabricksLogging.scala:77)
	at com.databricks.spark.util.DatabricksLogging.recordOperation$(DatabricksLogging.scala:67)
	at org.apache.spark.sql.delta.commands.VacuumCommand$.recordOperation(VacuumCommand.scala:49)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordDeltaOperation(DeltaLogging.scala:106)
	at org.apache.spark.sql.delta.metering.DeltaLogging.recordDeltaOperation$(DeltaLogging.scala:91)
	at org.apache.spark.sql.delta.commands.VacuumCommand$.recordDeltaOperation(VacuumCommand.scala:49)
	at org.apache.spark.sql.delta.commands.VacuumCommand$.gc(VacuumCommand.scala:101)
	at io.delta.tables.execution.DeltaTableOperations.executeVacuum(DeltaTableOperations.scala:74)
	at io.delta.tables.execution.DeltaTableOperations.executeVacuum$(DeltaTableOperations.scala:70)
	at io.delta.tables.DeltaTable.executeVacuum(DeltaTable.scala:42)
	at io.delta.tables.DeltaTable.vacuum(DeltaTable.scala:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

**Comment by tdas** [comment] 2021-12-14 23:44
This is a very odd issue. I am not sure I understand this issue off the top of my head. The error and the stack trace says that it failed in the middle of delete files (either listing files or actually deleting them), not in the middle of any interactions with glue. So I am not sure how this is related to Glue version upgrade. 

Is this is a reproducible issue?

**Comment by laksh9** [comment] 2021-12-16 17:03
I am getting similar error when i switch from glue 2.0 which uses spark 2.4 to glue 3.0 which uses spark 3.1

**Comment by julianste** [comment] 2021-12-17 19:51
@tdas thanks for looking into it.
We isolated the vacuum call into a separate glue job with Glue 2.0, which is triggered (via Airflow) after our main pipeline run with Glue 3.0. So this is okay for now, but with Glue 2.0 / Delta 0.6.1 vacuum is very slow, so I think it would be beneficial to be able to upgrade to Glue 3.0. 
For us the behavior is reproducible, using Glue 3, the vacuum glue job just always fails with the same stack trace (above), whereas with Glue 2 it works flawlessly.

**Comment by zsxwing** [comment] 2022-02-07 19:59
@julianste This sounds like a Spark bug rather than an issue in Delta or Glue. Probably a regression introduced between Spark 2.4 and 3.1.

By the way, have you enabled `spark.sql.adaptive.enabled`? If so, could you try to disable it and see if this is reproducible?

**Comment by fibona44i** [comment] 2022-02-08 22:47
We are experiencing same issue with glue 3.0 + datalake 1.0 during the merge of dataframe using delta.
I discovered that it is somehow related to the security configuration of Glue job.
Without security configuration, it works as expected.

**Comment by fibona44i** [comment] 2022-02-09 20:23
I think this is related to the following issue: https://issues.apache.org/jira/browse/SPARK-34790 (Fail in fetch shuffle blocks in batch when i/o encryption is enabled.)
And glue is using spark 3.1.1 :(

**Comment by zsxwing** [comment] 2022-02-22 18:15
Since this is a Spark issue, I'm going to close it. Feel free to re-open it if there is any other update.

**Closed by zsxwing** 2022-02-22 18:15 UTC
Labels: bug, acknowledged

**Comment by Mohammedhussen** [comment] 2022-03-09 03:44
@fibona44i @fibona44i I am facing similar issue while trying to read and write to S3 as delta table using aws glue 3.0. What are exactly your configuration? Could you please help?

**Comment by sparkcoder234** [comment] 2022-03-27 02:03
@fibona44i @zsxwing @Mohammedhussen @tdas Is there a solution for this? I am using delta lake 1.0.1, spark 3.1 and glue 3.0. I get the error **_An error occurred while calling 0234.vacuum. Job aborted due to stage failure: ResultStage_**
It doesn't fail all the time..but sometimes it just fails with vaccum error. Is there a fix for this?

**Comment by fibona44i** [comment] 2022-03-31 09:33
I already explained solution in following comment 
https://github.com/delta-io/delta/issues/841#issuecomment-1034159558
