### ISSUE TITLE
[BUG] DeltaTable.details() not exist in v2.0.x

### ISSUE THREAD

**Issue by changzhiwin** [delta-io/delta#1333] opened 2022-08-12 10:40 UTC
### Describe the problem
Source code at `$delta/examples/scala/src/main/scala/example/Utilities.scala` is out of date.
```
// not exist at v2.0.1, should remove
deltaTable.details().show()
```

### Environment information
* Delta Lake version: 2.0.1
* Spark version: 3.2.1
* Scala version: 2.13.8

#### Steps to reproduce
* 1, `cd examples/scala` 
* 2, run `./build/sbt`

**Comment by sherlockbeard** [comment] 2022-08-12 12:37
details function was requested in #1188 . and i am seeing it was merged (https://github.com/delta-io/delta/commit/5b214dd5456fac5a99aea8f8b782a37290d17165) yesterday.
i think it's not a bug . 
can build the latest snapshot of delta lake and try to run the example again .

**Comment by changzhiwin** [comment] 2022-08-12 14:33
I checked the master's source code, found this method. It since 2.1.0, so I used wrong version. 
```
  /**
   * Get the details of a Delta table such as the format, name, and size.
   *
   * @since 2.1.0
   */
  def details(): DataFrame = {
    executeDetails(deltaLog.dataPath.toString, table.getTableIdentifierIfExists)
  }
```
thanks a lot @sherlockbeard.

**Closed** 2022-08-12 15:31 UTC
Labels: bug
