### ISSUE TITLE
Support orc?

### ISSUE THREAD

**Issue by melin** [delta-io/delta#238] opened 2019-11-05 02:05 UTC
the orc community has developed faster and more performance

**Comment by it-sceptic** [comment] 2020-02-02 04:20
Agree with @melin

**Comment by tdas** [comment] 2020-02-05 00:11
This is definitely something that would be a good addition. However, there are a few things to consider before building this as pointed out as questions by @marmbrus in this issue -https://github.com/delta-io/delta/issues/87#issuecomment-509730048

**Comment by zsxwing** [comment] 2021-04-07 04:28
Closing this as duplicate of #87

**Closed by zsxwing** 2021-04-07 04:28 UTC
