### ISSUE TITLE
[BUG] testColumnMapping("block CONVERT TO DELTA") fails with "Illegal table name" on macOS

### ISSUE THREAD

**Issue by jaceklaskowski** [delta-io/delta#1286] opened 2022-07-23 11:25 UTC
### Describe the problem

```console
$ build/sbt 'core/testOnly *.DeltaColumnMappingSuite -- -z "block CONVERT TO DELTA"'
...
[info] - block CONVERT TO DELTA *** FAILED *** (3 seconds, 426 milliseconds)
[info]   Testing under mode: name Expected exception java.lang.UnsupportedOperationException to be thrown, but org.apache.spark.sql.catalyst.parser.ParseException was thrown (DeltaColumnMappingSuite.scala:1011)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
...
[info]   Cause: org.apache.spark.sql.catalyst.parser.ParseException: Illegal table name parquet./private/var/folders/k_/4tl__g7d589cw78q8f11ykrw0000gn/T/spark-9f8c3862-387f-4457-ba30-60f6d1139f90(line 1, pos 17)
[info]
[info] == SQL ==
[info] convert to delta parquet.`/private/var/folders/k_/4tl__g7d589cw78q8f11ykrw0000gn/T/spark-9f8c3862-387f-4457-ba30-60f6d1139f90` partitioned by (key1 String)
[info] -----------------^^^
[info]   at io.delta.sql.parser.DeltaSqlAstBuilder.$anonfun$visitTableIdentifier$1(DeltaSqlParser.scala:252)
[info]   at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:133)
[info]   at io.delta.sql.parser.DeltaSqlAstBuilder.visitTableIdentifier(DeltaSqlParser.scala:249)
...
```

### Environment information

* Delta Lake version: commit 56e1b9b417e8815cd7003eaf1796988c670b8b0d
* macOS Big Sur 11.6.6
* openjdk version "11.0.15" (Temurin-11.0.15+10 (build 11.0.15+10))

**Comment by sherlockbeard** [comment] 2022-07-25 17:13
delta lake only works with JDK 1.8 right ?
from Readme 
```
Under Project JDK specify a valid Java 1.8 JDK and opt to use SBT shell for project reload and builds.
```
or is it supposed to work with all JDK versions?

**Comment by bogdanmrusu** [comment] 2022-07-26 15:34
I tested with both JDK 1.8 and JDK 11 and I cannot reproduce.
Builds: `OpenJDK Runtime Environment (build 1.8.0_322-bre_2022_02_28_15_01-b00)` and `OpenJDK Runtime Environment Homebrew (build 11.0.12+0)`. 
MacOs: `Monterey 12.4`

It's not clear for me either with what JDK versions it should work.

**Comment by scottsand-db** [comment] 2022-08-02 17:22
@jaceklaskowski could you try again with JDK 1.8?

**Comment by zsxwing** [comment] 2022-09-14 17:18
Closing this as we cannot reproduce this. Feel free to re-open it if there is new update.

**Closed by zsxwing** 2022-09-14 17:18 UTC
Labels: bug
