### ISSUE TITLE
Delta 0.8.0 under Spark 3.1.1 throws NoSuchMethodError when invoking updateExpr method on deltaTable

### ISSUE THREAD

**Issue by unical1988** [delta-io/delta#630] opened 2021-03-24 23:58 UTC
Hello,

The error is the following : 
`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Alias.<init>(Lorg/apache/spark/sql/catalyst/expressions/Expression;Ljava/lang/String;Lorg/apache/spark/sql/catalyst/expressions/ExprId;Lscala/collection/Seq;Lscala/Option;)V`

Spark version : 
```
<groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.12</artifactId>
            <version>3.1.1</version>
```
Delta Version : 
```
<groupId>io.delta</groupId>
            <artifactId>delta-core_2.12</artifactId>
            <version>0.8.0</version>
```

**Comment by tdas** [comment] 2021-03-25 00:26
delta 0.8.0 is not compatible with spark 3.1 yet. we are in the process of migrating our master branch to be 3.1 compatible. next release will be compatible with 3.1.

**Comment by unical1988** [comment] 2021-03-25 07:51
Even 0.7.0 version of delta is not !

**Comment by jaceklaskowski** [comment] 2021-03-26 10:20
> Even 0.7.0 version of delta is not

At the time of 0.7.0 Spark 3.1.1 was not _even_ available so I consider it expected 😏

**Comment by jaceklaskowski** [comment] 2021-03-26 10:26
Duplicate of https://github.com/delta-io/delta/issues/594

**Comment by michaelli916** [comment] 2021-04-02 03:27
I am using insert sql to insert into a  delta table, the statement is like "insert into delta_test_table1 values (current_date(),'eventid1','eventtype1','data1');", 
and i see the same error when using  delta-core_2.12-0.8.0 against spark-3.1.1-bin-hadoop2.7, which is officically released by spark, while i don't see the issue when using delta-core_2.12-0.8.0 against spark-3.0.2-bin-hadoop2.7-hive1.2.

So i guess, yes, delta 0.8.0 is not compatible with spark-3.1.1. 
Look forward to the patch release of delta 0.8.0, which should be compatible with spark 3.1.1 on this sql insert issue.

**Comment by dishkakrauch** [comment] 2021-04-06 14:34
Also faced this problem using spark 3.1.1 and delta 0.8.0.
When will be delta patch released?

**Comment by zsxwing** [comment] 2021-04-06 23:41
Closing this. Please check #594 for the latest status.

**Closed by zsxwing** 2021-04-06 23:41 UTC
