### ISSUE TITLE
BUG: SparkStreaming in update mode with match operation to a DeltaLake sink produces "WARN HDFSBackedStateStoreProvider: The state for version 1 doesn't exist in loadedMaps" when print operations are performed in foreachbatch

### ISSUE THREAD

**Issue by e-compagno** [delta-io/delta#649] opened 2021-04-08 16:30 UTC
I am using spark 3.0.1 and delta lake 0.8.0. I am using spark stream in update mode to write to a delta lake sink (with a match operation). 

I have found out that when a `println` operations is performed inside a `foreachBatch` body, a warning message

```WARN HDFSBackedStateStoreProvider: The state for version ... doesn't exist in loadedMaps. Reading snapshot file and delta files if needed...Note that this is normal for the first batch of starting query.```

is generated every new data batch. However, when the `println` is removed in the `foreachbatch` operation no warning is produced.

<img width="1029" alt="Screenshot 2021-04-08 at 17 21 46" src="https://user-images.githubusercontent.com/49021750/114061972-e7670b00-988e-11eb-870b-dd01d3efa83c.png">

In the code below a stream of two columns (an integer and a random label ("red", "yellow", "blue")) is generated using a "rate" source. Then data is grouped by label and the integers are collected to a list. The output is written in update mode with a merge operation to a delta lake.

Please find the code below:
```
/* TestDataLakeError.scala */

package TestDeltaLake

import org.apache.spark.sql.{DataFrame, Encoders, Row}
import io.delta.tables._
import org.apache.spark.sql.functions.{collect_list, udf}

import scala.reflect.io.Directory
import java.io.File
import scala.util.Random

case class DeltaLakeSink(label: String, value: Array[Int])

object TestDeltaLakeError extends App {
  val spark: SparkSession = {
    SparkSession
      .builder()
      .appName("TestDeltaLake")
      .master("local[*]")
      .config("spark.eventLog.enabled", "false") 
      .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") 
      .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
      .getOrCreate()
  }
  val sc: SparkContext = spark.sparkContext
  val conf = sc.hadoopConfiguration

  import spark.implicits._
  val deltaTablePath: String = "src/main/resources/deltalake"

  val deltaLakeSchema = Encoders.product[DeltaLakeSink].schema

  /**
   * Get a random label among yellow, blue and red
   * @return label
   */
  def getRandomLabel(): String = {
    val labelsList: Seq[String] = Seq("yellow", "blue", "red")
    val random = new Random
    labelsList(random.nextInt(labelsList.length))
  }

  /* create a udf for generating a column of random labels */
  val getRandomLabelUDF = udf(getRandomLabel _)

  /**
   * Create an empty DeltaLake
   * @param deltaTablePath path to deltalake
   */
  def generateEmptyDeltaLake(deltaTablePath: String): Unit = {
    /* Create an empty DeltaLake table */
    val isDeltaTable = DeltaTable.isDeltaTable(deltaTablePath)

    /* Delete and create an empty DeltaLake */
    if(isDeltaTable){
      val dLakeFolder = new Directory(new File(deltaTablePath))
      dLakeFolder.deleteRecursively()
    }

    val emptyDF = {
      spark
        .createDataFrame(spark.sparkContext.emptyRDD[Row], deltaLakeSchema)
    }
    emptyDF
      .write
      .format("delta")
      .mode("overwrite")
      .save(deltaTablePath)
  }

  /* Generate a sample data stream grouping by labels */
  val inputStreamDF: DataFrame = {
    spark
      .readStream
      .format("rate")
      .load()
      .drop("timestamp")
      .withColumn("label", getRandomLabelUDF())
      .groupBy("label")
      .agg(collect_list($"value").as("value"))
  }

  /**
   * Function to store new batch data in delta lake
   * @param batchDF input batch dataframe
   * @param batchId id of the batch
   */
  def upsertToDeltaLake(batchDF: DataFrame, batchId: Long): Unit = {
    DeltaTable
      .forPath(spark, deltaTablePath)
      .as("dLakeDF")
      .merge(
        batchDF.as("batchDF"),
        "dLakeDF.label = batchDF.label"
      )
      .whenMatched().updateAll()
      .whenNotMatched().insertAll()
      .execute()
  }

  /* Initialise an empty delta lake */
  generateEmptyDeltaLake(deltaTablePath)

  /* Update new data to delta lake*/
  inputStreamDF
    .writeStream
    .foreachBatch{
      (batchDF: DataFrame, batchId: Long) =>
        {
          /* IF THE NEXT LINE IS COMMENTED THE WARN DOES NOT HAPPEN */
          println(s"batchId: ${batchId}, batchDF count: ${batchDF.count()}")
          upsertToDeltaLake(batchDF, batchId)
        }
    }
    .outputMode("update")
    .start()
    .awaitTermination()
}
```

**Comment by tdas** [comment] 2021-04-12 23:25
`HDFSBackedStateStoreProvider` is not related to Delta Lake, and is related to state management in Structured Streaming. Specifically, this is a relatively harmless warning! It just does that only when starting the streaming query, when none of the state data is loaded in the Spark executor memory, and therefore needs to be retrieved from the checkpoint location. So as far as I see, there are no issues here.

**Comment by e-compagno** [comment] 2021-04-13 08:18
Thank you for your reply. However, what is curious is that if you remove the `println` line the error disappears. In the same way by removing the `upsertToDeltaLake(batchDF, batchId)` line the error is gone too. Moreover, the error appears every new batch, not only for the first. 

I understand it's possible just a harmless warning, but I suppose this is not the normal way it should work (at least the warn should be muted). Anyhow, if you don't think this is a bug please feel free to close this issue.

**Comment by tdas** [comment] 2021-04-14 05:11
if removing println is changing something, then that is weird. my suspicion is that the println is messing with the log4j WARN level configuration and making it disappear. Only a guess. 

What is it printing in the following batches? is it saying "state for version X" where X is incrementing with batches?

**Comment by jaceklaskowski** [comment] 2021-04-14 07:45
Please note that saying _"if you remove the println line the error disappears"_ could imply that the `println` itself is the root cause but it's not. It's what happens in the `println` which is `batchDF.count()` that triggers a Spark job to count the rows. That in turn triggers a whole lot of Spark processing incl. Delta Lake state reconstruction and such. In other words, that's one more Delta Lake's execution. Makes sense?

**Comment by e-compagno** [comment] 2021-04-14 08:04
Yes, the following batches print the same warning: 
<img width="1192" alt="Screenshot 2021-04-14 at 09 03 28" src="https://user-images.githubusercontent.com/49021750/114675560-48b03380-9d00-11eb-9c28-fe647d2d4f09.png">

In any case I totally agree with you. Indeed by leaving `batchDF.count()` but removing the `println` generates the same issue

**Comment by tdas** [comment] 2021-04-14 21:28
good point @jaceklaskowski I was assuming that the upsert function was trigger all the Spark job to compute the streaming state anyways. my new guess is that the warning is somehow caused by making multiple jobs on the same foreachBatch dataframe. again, its not a correctness issue as the state management should be robust to extra reloading of state stores, and the multiple jobs in foreach batch is hitting that rare, but correctly handled corner case of the state management causing warnings. either way definitely not a delta issue, hence closing this ticket.

**Closed by tdas** 2021-04-14 21:28 UTC
