### ISSUE TITLE
Enable Change Data Feed

### ISSUE THREAD

**Issue by TioLuiso** [delta-io/delta#704] opened 2021-06-21 13:48 UTC
We are developing an application for Azure Databricks. We are using DBR 8.3, which has the experimental feature of Change Data Feed.
For testing purposes, we have a dockerized local environment with Spark 3.1.2 and spark-delta 1.0.0. When we want to create a CDF enabled table, we use:

`DeltaTable.createIfNotExists(spark).tableName("TableName").addColumns(schema).location(path).property("delta.enableChangeDataFeed", "true").execute()`

When we try to execute that, we receive the error:

`Configuration delta.enableChangeDataFeed cannot be set. Change data feed from Delta is not yet available.`

Is there anyway to enable this for local testing purposes?

**Comment by tdas** [comment] 2021-06-21 17:19
CDF is only available in Delta on Databricks right now. So using Delta 1.0 locally will not allow you to use CDF.

**Comment by TioLuiso** [comment] 2021-06-21 18:46
Thanks a lot for your response
Ok, I see.
Is it expected that eventually CDF could be used out of Databricks? Is there something in the works there?
Anyway, thanks a lot

**Comment by dennyglee** [comment] 2021-10-12 01:56
Hi @TioLuiso - a great way to chime in is to vote in the Delta OSS 2021H2 Roadmap - here's [the link](https://github.com/delta-io/delta/issues/748#issuecomment-920642051) specifically to CDF.  HTH!

**Comment by scottsand-db** [comment] 2022-04-29 21:27
@TioLuiso - see https://github.com/delta-io/delta/issues/1105.

**Comment by igvog** [comment] 2022-06-28 06:28
Looking forward to adding CDF to Delta OSS! @dennyglee

**Comment by dennyglee** [comment] 2022-07-11 22:29
Definitely!  We're marching towards Delta Lake 2.0 ([the RC](https://github.com/delta-io/delta/releases/tag/v2.0.0rc1) became available for testing in late June).  Test it out now if you can and provide us feedback, eh?! :)

**Comment by zsxwing** [comment] 2022-07-27 07:17
2.0.0 has been released. Closing this as a duplicate of #1105

**Closed by zsxwing** 2022-07-27 07:17 UTC
Labels: enhancement
